[package]
name = "RestRust"
version = "0.1.0"
authors = ["GONZALO MATEOS GLEZ-SICILIA <aria.support@repsol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
